services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: miau
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
    driver: local